version: "3.3"

services:
  db-idemiafoot:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - idemiafoot-data:/var/lib/mysql
    ports:
      - "3306:3306"

  idemiafoot-back:
    depends_on:
      - db-idemiafoot
    env_file:
      - /home/ubuntu/.env
    image: loicverniere/idemiafoot-back:main
    restart: always
    environment:
      DB_HOST: db-idemiafoot
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idemiafoot-back.rule=Host(`api.foot-idemia.fr`)"
      - "traefik.http.routers.idemiafoot-back.entrypoints=websecure"
      - "traefik.http.routers.idemiafoot-back.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.idemiafoot-back.service=idemiafoot-service"
      - "traefik.http.services.idemiafoot-service.loadbalancer.server.port=3000"
    volumes:
      - "/home/ubuntu/.env:/app/.env"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.letsencryptresolver.acme.httpChallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpChallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=foot.idemia@gmail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  idemiafoot-data:
