version: "3.3"

services:
  db-idemiafoot:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - idemiafoot-data:/var/lib/mysql
    ports:
      - "3306:3306"