version: "3.3"

services:
  db-idemiafoot:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db-idemiafoot
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "3306:3306"
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "9000:9000"
