version: "3.3"

services:
  db-idemiafoot:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - idemiafoot-data:/var/lib/mysql
    ports:
      - "3306:3306"

  idemiafoot-back:
      image: loicverniere/idemiafoot-back:main
      restart: always
      environment:
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
        REFRESH_TOKEN: ${REFRESH_TOKEN}
        EMAIL: ${EMAIL}
      ports:
        - "3000:3000"

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.httpChallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpChallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=foot.idemia@gmail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.foot-idemia.fr`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.whoami.middlewares=redirect@docker"

volumes:
  idemiafoot-data:
  
