name: Build, Push Docker image and Deploy

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Build, Push Docker image to Docker Hub and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: loicverniere/idemiafoot-back
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .  
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Oracle Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 129.151.232.234 >> ~/.ssh/known_hosts
          ssh ubuntu@129.151.232.234 "if [ ! -d ~/idemiafoot-back ]; then mkdir -p ~/idemiafoot-back; fi"
          scp docker-compose.yml ubuntu@129.151.232.234:~/idemiafoot-back
          ssh ubuntu@129.151.232.234 "source ~/.env"
          ssh ubuntu@129.151.232.234 "if [ \"$(docker ps -aq -f name=idemiafoot-back)\" ]; then docker stop idemiafoot-back; fi"
          ssh ubuntu@129.151.232.234 "if [ \"$(docker ps -aq -f name=idemiafoot-back)\" ]; then docker rm idemiafoot-back; fi"
          ssh ubuntu@129.151.232.234 "docker pull loicverniere/idemiafoot-back:main"
          ssh ubuntu@129.151.232.234 "export DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} && export DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} && export DB_DATABASE=${{ secrets.MYSQL_DATABASE }} && cd ~/idemiafoot-back && docker-compose pull && docker-compose up -d"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
