name: Deploy NestJS to Oracle Cloud

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Oracle Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 129.151.232.234 >> ~/.ssh/known_hosts
          ssh ubuntu@129.151.232.234 "if [ ! -d ~/idemiafoot-back ]; then mkdir -p ~/idemiafoot-back; fi"
          ssh ubuntu@129.151.232.234 "if [ \"$(docker ps -aq -f name=idemiafoot-back)\" ]; then docker stop idemiafoot-back; fi"
          ssh ubuntu@129.151.232.234 "if [ \"$(docker ps -aq -f name=idemiafoot-back)\" ]; then docker rm idemiafoot-back; fi"
          ssh ubuntu@129.151.232.234 "docker pull loicverniere/idemiafoot-back:latest"
          ssh ubuntu@129.151.232.234 "export MYSQL_ROOT_PASSWORD=*** && export MYSQL_DATABASE=*** && export CLIENT_ID=*** && export CLIENT_SECRET=*** && export EMAIL=*** && export REFRESH_TOKEN=*** && cd ~/idemiafoot-back && docker-compose pull && docker-compose up -d"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
